#include "nsISupports.idl"

[scriptable, uuid(3146FBBB-CBDF-4A0F-BC00-00CAD2C75E58)]
interface IDockProgress : nsISupports
{
  const long STYLE_BAR = 0;
  const long STYLE_FILL = 1;

  void SetHidden();
  void SetProgress(in double percent);
  void SetGradientPath(in AUTF8String path);
  void SetStyle(in long style);
};
